# Generated by Django 5.0.1 on 2024-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
